put:
  description: Upload file to S3.
  fields:
    bucket:
      description: S3 bucket to receive upload
      example: my_bucket
    key:
      description: key to use
      example: my_key/snapshot.jpg
    content_type:
      description: Content type to set on uploaded object
      example: "application/json"
    file_path:
      description: File on local filesystem to upload
      example: /data/camera_files/snapshot.jpg
    tags:
      description: Tags to add to uploaded object URL encoded
      example: "tag1=value1&tag2=value2"
    storage_class:
      description: S3 storage class (defaults to STANDARD) [ STANDARD | REDUCED_REDUNDANCY | STANDARD_IA | ONEZONE_IA | INTELLIGENT_TIERING | GLACIER | DEEP_ARCHIVE ]
      example: STANDARD_IA
copy:
  description: Copy file from one location in s3 to another.
  fields:
    bucket:
      description: Source and destination S3 bucket
      example: my_bucket
    key_source:
      description: key to copy from
      example: my_key/snapshot.jpg
    key_destination:
      description: key to copy to
      example: my_key/snapshot.jpg
delete:
  description: Delete object from S3.
  fields:
    bucket:
      description: S3 bucket to delete from
      example: my_bucket
    key:
      description: key of object to delete
      example: my_key/snapshot.jpg
signurl:
  description: Create pre-signed URL for S3 object.
  fields:
    bucket:
      description: S3 bucket of file
      example: my_bucket
    key:
      description: key of object
      example: my_key/snapshot.jpg
    duration:
      description: validity period in seconds of url.
      example: 360
